# Setup
title: gm.me.uk
tagline: Playing with the sand at the side of the road
url: https://gm.me.uk
paginate: 1
paginate_path: /blog/page/:num
archive_path: /blog/archive
baseurl: ""
permalink: /blog/:year/:month/:day/:title/
timezone: Europe/London
locale: en_GB

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name: Gerard Martin
  github: gerjomarty
  twitter: gerjomarty

twitter:
  username: gerjomarty
  card: summary
